version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 8
    commit-message:
      prefix: "chore"
      include: scope
    labels:
      - dependencies
      - github-actions
    ignore:
      - dependency-name: dtolnay/rust-toolchain
    groups:
      actions:
        patterns:
          - "*"
        exclude-patterns:
          - dtolnay/rust-toolchain
